

typeset -U path cdpath fpath manpath

ZSH=/usr/share/oh-my-zsh/
ZSH_THEME="lambda"

plugins=(archlinux
	asdf
	bundler
	docker
	jsontools
	vscode
	web-search
	tig
    fzf-tab
	gitfast
	colored-man-pages
	colorize
	command-not-found
	cp
	dirhistory
	sudo
	zsh-syntax-highlighting)

# Zoxide 
eval "$(zoxide init zsh)"

# History options should be set in .zshrc and after oh-my-zsh sourcing.
# See https://github.com/nix-community/home-manager/issues/177.
HISTSIZE="10000"
SAVEHIST="10000"

HISTFILE="$HOME/.zsh_history"
mkdir -p "$(dirname "$HISTFILE")"

setopt HIST_FCNTL_LOCK
setopt HIST_IGNORE_DUPS
unsetopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
unsetopt HIST_EXPIRE_DUPS_FIRST
setopt SHARE_HISTORY
unsetopt EXTENDED_HISTORY


export EDITOR='nvim'

bin_txt() {
    curl -X PUT --data "$1" https://p.spanskiduh.dev
}

bin_file() {
    curl -X PUT --data-binary "@$1" https://p.spanskiduh.dev
}

# Aliases
alias -- 'md-notes'='cd ~/Documents/md-notes/ && nvim .'
alias -- 'ndevelop'='nix develop -c $SHELL'
alias -- 'night'='brightnessctl s 1%'
alias -- 'opdf'='okular $(find ~/  -type f -iname '\''*pdf'\'' | fzf)'
alias -- 'rebuild-os'='sudo nixos-rebuild switch --flake /home/spagnologasper/.config/home-manager#yoga'
alias -- 'rm'='rm -i'
alias -- 'rot13'='tr '\''A-Za-z'\'' '\''N-ZA-Mn-za-m'\'''
alias -- 'ss'='grc ss'
alias -- 'sup'='power off'
alias -- 'sur'='systemctl reboot'
alias -- 'sus'='systemctl suspend'
alias -- 'tree'='eza --tree'
alias -- 'vi'='nvim'
alias -- 'vim'='nvim'

# Named Directory Hashes

source $ZSH/oh-my-zsh.sh

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
typeset -gA ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[cursor]='bold'

ZSH_HIGHLIGHT_STYLES[alias]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[function]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[command]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=green,bold'

# Ctrl-O opens zsh at the current location, and on exit, cd into ranger's last location.
ranger-cd() {
	tempfile=$(mktemp)
	ranger --choosedir="$tempfile" "${@:-$(pwd)}" < $TTY
	test -f "$tempfile" &&
	if [ "$(cat -- "$tempfile")" != "$(echo -n `pwd`)" ]; then
	cd -- "$(cat "$tempfile")"
	fi
	rm -f -- "$tempfile"
	# hacky way of transferring over previous command and updating the screen
	VISUAL=true zle edit-command-line
}
zle -N ranger-cd
bindkey '^o' ranger-cd

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

ZSH_CACHE_DIR=$HOME/.cache/oh-my-zsh
if [[ ! -d $ZSH_CACHE_DIR ]]; then
  mkdir $ZSH_CACHE_DIR
fi

source $ZSH/oh-my-zsh.sh
