---
sys_username: spanskiduh
sys_hostname: t14
arch_mirror_country: Germany,Austria,Slovenia
use_wayland: true

base_packages:
  - openssh
  - bind
  - dialog
  - intel-ucode
  - git
  - reflector
  - bash-completion
  - w3m
  - base-devel
  - lshw
  - zip
  - unzip
  - htop
  - xsel
  - tree
  - fuse2
  - keychain
  - arandr
  - powertop
  - inxi
  - wget
  - iw
  - wpa_supplicant
  - openbsd-netcat
  - axel
  - tcpdump
  - mtr
  - net-tools
  - rsync
  - conntrack-tools
  - ethtool
  - go
  - ripgrep
  - brightnessctl
  - oh-my-zsh-git
  - yamlfmt
  - ntfs-3g
  - net-tools
  - inetutils
  - lua-format
  - direnv
  - tk # for python
  - ttf-iosevka
  - imagemagick
  - micromamba-bin

desktop_packages:
  - brave-bin
  - discord
  - libreoffice
  - fontforge
  - gparted
  - obs-studio
  - vlc
  - remmina
  - neofetch
  - evince
  - gimp
  - shotwell
  - file-roller
  - shotcut
  - inkscape
  - evolution
  - mousepad
  - klavaro
  - texlive
  # Pdf viewer
  - zathura
  - zathura-pdf-mupdf
  - ranger
  # GUI File explorer - thunar
  - thunar
  - thunar-volman
  - thunar-archive-plugin
  - thunar-media-tags-plugin
  - alacritty
  - lxappearance
  # Music 
  - spotify
  - cava
  # Others
  - qt5ct

hacking_packages:
  - ghidra
  - wireshark-qt
  - dig
  - hyperscan
  - imhex-bin
  - radare2
  - burpsuite

sound_packages:
  - sof-firmware
  - alsa-utils
  - alsa-plugins
  - pavucontrol
  - pipewire-alsa
  - pipewire-pulse
  - pipewire-jack

sway_packages:
  - sway
  - waybar
  - wofi
  - xorg-xwayland
  - xorg-xlsclients
  - qt5-wayland
  - glfw-wayland
  - wl-clipboard
  - grim
  - slurp
  - mako
  - bemenu
  - swaylock
  - swayidle
  - swaybg
  - wdisplays
  - xdg-desktop-portal-wlr
  - xdg-desktop-portal
  - kanshi
  - nwg-bar

xorg_packages:
  - xorg
  - xorg-apps
  - xorg-xinit
  - xdotool
  - xclip
  - xorg-drivers

i3_packages:
  - i3-wm
  - i3status
  - i3lock
  - lxappearance
  - polybar
  - rofi
  - ranger
  - thunar
  - alacritty
  - dunst
  - feh
  - xss-lock
  - picom
  - light
  - pango
  - flameshot
  - gsimplecal
  - thunar-archive-plugin
  - thunar-media-tags-plugin
