sys_username: spanskiduh
sys_hostname: t14
arch_mirror_country: Germany,Austria,Slovenia
use_wayland: true

base_packages:
  # Essential utilities
  - base-devel
  - bash-completion
  - dialog
  - keychain
  - lshw
  - inxi
  - htop
  - tree
  - xsel
  - fuse2
  - zip
  - unzip
  - imagemagick
  - micromamba-bin
  - tk  # for python
  - intel-ucode

  # Networking tools
  - openssh
  - iw
  - wpa_supplicant
  - openbsd-netcat
  - axel
  - tcpdump
  - mtr
  - net-tools
  - inetutils
  - rsync
  - conntrack-tools
  - ethtool

  # Package management & mirrors
  - reflector
  - go
  - ripgrep
  - yamlfmt
  - lua-format
  - direnv

  # Miscellaneous utilities
  - ntfs-3g
  - brightnessctl
  - powertop
  - arandr
  - w3m
  - wget
  - oh-my-zsh-git

desktop_packages:
  # Browsers & communication
  - brave-bin
  - discord
  - betterdiscord-installer # betterdiscord-installer install
  - evolution
  - remmina

  # Office & productivity
  - libreoffice
  - gparted
  - evince
  - zathura
  - zathura-pdf-mupdf
  - texlive

  # Media & design
  - vlc
  - gimp
  - shotcut
  - inkscape
  - fontforge
  - obs-studio
  - file-roller
  - shotwell

  # File management
  - ranger
  - thunar
  - thunar-volman
  - thunar-archive-plugin
  - thunar-media-tags-plugin
  - thunar-nextcloud-plugin
  - tumbler # thumbnailer

  # Terminal & UI customization
  - alacritty
  - lxappearance
  - qt5ct
  - neofetch
  - mousepad

  # Music
  - spotify
  - cava

  # Typing tutor
  - klavaro

hacking_packages:
  - ghidra
  - wireshark-qt
  - dig
  - hyperscan
  - imhex-bin
  - radare2
  - burpsuite

sound_packages:
  - sof-firmware
  - alsa-utils
  - alsa-plugins
  - pavucontrol
  - pipewire-alsa
  - pipewire-pulse
  - pipewire-jack

sway_packages:
  - sway
  - swaybg
  - swayidle
  - swaylock-effects
  - waybar
  - wofi
  - mako
  - bemenu
  - wdisplays
  - xdg-desktop-portal-wlr
  - xdg-desktop-portal
  - kanshi
  - nwg-bar

  # Clipboard & screenshot tools
  - wl-clipboard
  - grim
  - slurp

  # XWayland compatibility
  - xorg-xwayland
  - xorg-xlsclients

  # Wayland-specific libraries
  - qt5-wayland
  - glfw-wayland

xorg_packages:
  - xorg
  - xorg-apps
  - xorg-xinit
  - xdotool
  - xclip
  - xorg-drivers

i3_packages:
  - i3-wm
  - i3status
  - i3lock
  - lxappearance
  - polybar
  - rofi
  - ranger
  - thunar
  - alacritty
  - dunst
  - feh
  - xss-lock
  - picom
  - light
  - pango
  - flameshot
  - gsimplecal
  - thunar-archive-plugin
  - thunar-media-tags-plugin
