sys_username: spanskiduh
sys_hostname: t14
arch_mirror_country: Germany,Austria,Slovenia
use_wayland: true

# --- NFTABLES CONFIGURATION ---

# Each rule can include the following keys:
# - description: A short description of the rule.
# - table: The nftables table (default: "inet filter")
# - chain: The chain within the table (default: "output")
# - protocol: The protocol (e.g., "tcp", "udp", "icmp")
# - dport: The destination port (optional, used with tcp/udp)
# - sport: The source port (optional)
# - action: The action to take (e.g., "reject", "accept", "drop")
# - rule: (optional) A complete, raw rule string to use instead of composing one.
#   If defined, this value takes precedence over protocol/dport/sport/action.
#
# A rule is added with an extra comment clause:
#   comment "ansible_rule_<DESCRIPTION>"

nft_rules:
-   description: Block_DNS_TCP
    table: inet filter
    chain: output
    protocol: tcp
    dport: 53
    action: reject with tcp reset
-   description: Block_DNS_UDP
    table: inet filter
    chain: output
    protocol: udp
    dport: 53
    action: reject

# --- PACKAGES ---

base_packages:
  # Essential utilities
-   base-devel
-   bash-completion
-   dialog
-   keychain
-   lshw
-   inxi
-   htop
-   tree
-   eza
-   xsel
-   fuse2
-   zip
-   unzip
-   imagemagick
-   micromamba-bin
-   tk  # for python
-   intel-ucode
-   zoxide
-   lsd
-   less
-   fprintd

  # Networking tools
-   openssh
-   sshpass
-   sshfs
-   iw
-   wpa_supplicant
-   openbsd-netcat
-   axel
-   tcpdump
-   mtr
-   net-tools
-   inetutils
-   rsync
-   conntrack-tools
-   ethtool

  # Package management & mirrors
-   reflector
-   go
-   ripgrep
-   ripgrep-all
-   yamlfmt
#-   lua-format
-   direnv

  # Miscellaneous utilities
-   ntfs-3g
-   brightnessctl
-   powertop
-   arandr
-   w3m
-   wget
-   oh-my-zsh-git
-   cliphist 
desktop_packages:
  # Browsers & communication
-   brave-bin
-   discord
-   slack-desktop
-   evolution
-   remmina

  # Office & productivity
-   libreoffice
-   gparted
-   evince
-   zathura
-   zathura-pdf-mupdf
-   xdotool
-   texlive
-   biber
-   okular

  # Media & design
-   vlc
-   gimp
-   shotcut
-   inkscape
-   fontforge
-   obs-studio
-   file-roller
-   shotwell
-   feh

  # File management
-   ranger
-   superfile
-   thunar
-   thunar-volman
-   thunar-archive-plugin
-   thunar-media-tags-plugin
-   thunar-nextcloud-plugin
-   tumbler # thumbnailer
-   fzf
-   fd
-   tree-sitter

  # Terminal & UI customization
-   alacritty
-   lxappearance
-   qt5ct
-   neofetch
-   mousepad

  # Music
-   spotify
-   cava

  # Typing tutor
-   klavaro

  # Clipboard tool
-   copyq

  # Programming
-   neovim
-   cursor-bin
-   uv
-   python-ruamel-yaml
-   jdk-openjdk
-   claude-code

  # Styling 
-   dracula-gtk-theme
-   dracula-icons-theme

hacking_packages:
-   ghidra
-   wireshark-qt
-   dig
-   hyperscan
-   imhex-bin
-   radare2
-   burpsuite

sound_packages:
-   sof-firmware
-   alsa-utils
-   alsa-plugins
-   pavucontrol
-   pipewire-alsa
-   pipewire-pulse

sway_packages:
-   sway
-   swaybg
-   swayidle
-   swaylock-effects
-   waybar
-   wofi
-   mako
-   bemenu
-   wdisplays-persistent
-   xdg-desktop-portal-wlr
-   xdg-desktop-portal
-   kanshi
-   nwg-bar

  # Clipboard & screenshot tools
-   wl-clipboard
-   grim
-   slurp

  # XWayland compatibility
-   xorg-xwayland
-   xorg-xlsclients

  # Wayland-specific libraries
-   qt5-wayland
-   glfw-wayland

xorg_packages:
-   xorg
-   xorg-apps
-   xorg-xinit
-   xdotool
-   xclip
-   xorg-drivers

i3_packages:
-   i3-wm
-   i3status
-   i3lock
-   lxappearance
-   polybar
-   rofi
-   ranger
-   thunar
-   alacritty
-   dunst
-   feh
-   xss-lock
-   picom
-   light
-   pango
-   flameshot
-   gsimplecal
-   thunar-archive-plugin
-   thunar-media-tags-plugin
