---
- import_playbook: playbooks/01-setup-paru.yml
- import_playbook: playbooks/02-setup-bluetooth.yml
- import_playbook: playbooks/03-setup-display-manager.yml
- import_playbook: playbooks/04-setup-fonts.yml
- import_playbook: playbooks/05-setup-themes.yml
- import_playbook: playbooks/06-setup-mirrors.yml
- import_playbook: playbooks/07-install-packages.yml
#- import_playbook: playbooks/08-setup-nvidia.yml
- import_playbook: playbooks/09-setup-battery-saving.yml
- import_playbook: playbooks/10-apply-dotfiles.yml
- import_playbook: playbooks/11-setup-copilot-neovim.yml
- import_playbook: playbooks/12-setup-default-shell.yml
- import_playbook: playbooks/13-setup-tmux-plugin-manager.yml
- import_playbook: playbooks/14-setup-docker.yml
- import_playbook: playbooks/15-setup-virt-manager.yml
- import_playbook: playbooks/16-setup-wireguard.yml
- import_playbook: playbooks/17-backlight.yml
