[colors]
[colors.bright]
black = "#5b5858"
blue = "#3fc4de"
cyan = "#6be4e6"
green = "#3fdaa4"
magenta = "#f075b5"
red = "#ec6a88"
white = "#d5d8da"
yellow = "#fbc3a7"

[colors.cursor]
cursor = "#e95678"
text = "#1c1e26"

[colors.dim]
black = "#16161c"
blue = "#26bbd9"
cyan = "#59e1e3"
green = "#29d398"
magenta = "#ee64ac"
red = "#e95678"
white = "#d5d8da"
yellow = "#fab795"

[colors.hints]
[colors.hints.end]
background = "#26bbd9"
foreground = "#1c1e26"

[colors.hints.start]
background = "#ee64ac"
foreground = "#1c1e26"

[[colors.indexed_colors]]
color = "#f5a97f"
index = 16

[[colors.indexed_colors]]
color = "#f4dbd6"
index = 17

[colors.normal]
black = "#16161c"
blue = "#26bbd9"
cyan = "#59e1e3"
green = "#29d398"
magenta = "#ee64ac"
red = "#e95678"
white = "#d5d8da"
yellow = "#fab795"

[colors.primary]
background = "#1c1e26"
bright_foreground = "#e0e0e0"
dim_foreground = "#e0e0e0"
foreground = "#e0e0e0"

[colors.search]
[colors.search.focused_match]
background = "#29d398"
foreground = "#1c1e26"

[colors.search.matches]
background = "#fab795"
foreground = "#1c1e26"

[colors.selection]
background = "#e95678"
text = "#1c1e26"

[colors.vi_mode_cursor]
cursor = "#26bbd9"
text = "#1c1e26"

[font]
size = 12
[font.normal]
#family = "Iosevka"
style = "Regular"

[window]
decorations = "None"
opacity = 0.9

[window.padding]
x = 5
y = 5
