[general]
live_config_reload = true

# Kanagawa Wave Alacritty Colors

[colors.primary]
background = '#1f1f28'
foreground = '#dcd7ba'

[colors.normal]
black = '#090618'
red = '#c34043'
green = '#76946a'
yellow = '#c0a36e'
blue = '#7e9cd8'
magenta = '#957fb8'
cyan = '#6a9589'
white = '#c8c093'

[colors.bright]
black = '#727169'
red = '#e82424'
green = '#98bb6c'
yellow = '#e6c384'
blue = '#7fb4ca'
magenta = '#938aa9'
cyan = '#7aa89f'
white = '#dcd7ba'

[colors.selection]
background = '#2d4f67'
foreground = '#c8c093'

[[colors.indexed_colors]]
index = 16
color = '#ffa066'

[[colors.indexed_colors]]
index = 17
color = '#ff5d62'

[colors.cursor]

text = "#282a36"
cursor = "#f8f8f2"

[colors.vi_mode_cursor]

text = "CellBackground"
cursor = "CellForeground"

[colors.search.matches]

foreground = "#44475a"
background = "#50fa7b"

[colors.search.focused_match]

foreground = "#44475a"
background = "#ffb86c"

[colors.footer_bar]

background = "#282a36"
foreground = "#f8f8f2"

[colors.hints.start]

foreground = "#282a36"
background = "#f1fa8c"

[colors.hints.end]

foreground = "#f1fa8c"
background = "#282a36"

[cursor]
style = { shape = "Beam", blinking = "On" }

[font]
size = 11
[font.normal]
family = "Iosevka"
style = "Regular"

[scrolling]
history = 10000
multiplier = 4

[window]
decorations = "None"
opacity = 0.9
dynamic_title = true
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "SpawnNewInstance"
