  - hosts: localhost
    become: true
    tasks:

      - name: Install Bluetooth packages
        pacman:
          name:
            - bluez
            - bluez-utils
            - blueman
            - blueberry
          state: present

      - name: Enable Bluetooth service
        ansible.builtin.systemd:
          name: bluetooth
          enabled: true
          state: started
