- hosts: localhost
  become: true
  tasks:


  - name: Install ly
    pacman:
      name: ly
      state: present


  - name: Enable ly service
    systemd:
      name: ly
      enabled: true
      state: started
