-   hosts: localhost
    become: true
    vars:
      font_packages:
      -   noto-fonts
      -   noto-fonts-emoji
      -   ttf-ubuntu-font-family
      -   ttf-dejavu
      -   ttf-freefont
      -   ttf-iosevka
      -   ttf-liberation
      -   ttf-droid
      -   ttf-roboto
      -   terminus-font
      -   ttf-jetbrains-mono-nerd
      -   ttf-font-awesome
    tasks:

    -   name: Install font packages with paru (batch installation)
        block:
        -   name: Debug - Show batch installation command
            debug:
              msg: "Running: paru -S --noconfirm {{ font_packages | join(' ') }}"

        -   name: Try batch installation first
            ansible.builtin.command: paru -S --noconfirm {{ font_packages | join(' ') }}
            become: false
            register: batch_result

        rescue:
        -   name: Log batch installation failure
            debug:
              msg: "Batch installation failed, trying individual packages. Error: {{ batch_result.stderr }}"

        -   name: Install packages individually
            ansible.builtin.command: paru -S --noconfirm {{ item }}
            loop: "{{ font_packages }}"
            become: false
            register: individual_results
            ignore_errors: true

        -   name: Report failed packages
            debug:
              msg: "Failed to install: {{ item.item }}"
            loop: "{{ individual_results.results }}"
            when: item.rc != 0

    -   name: Update font cache
        ansible.builtin.command: fc-cache -fv
        become: true
