---
- hosts: localhost
  become: yes
  tasks:
    - name: Install noto and ubuntu fonts
      pacman:
        name:
          - noto-fonts
          - noto-fonts-emoji
          - ttf-ubuntu-font-family
          - ttf-dejavu
          - ttf-freefont
        state: present

    - name: Install additional fonts
      pacman:
        name:
          - ttf-liberation
          - ttf-droid
          - ttf-roboto
          - terminus-font
        state: present
