-   hosts: localhost
    become: true
    tasks:

    -   name: Install theme
        ansible.builtin.command: paru -S --noconfirm dracula-gtk-theme
        become: false

    -   name: Set GTK theme via gsettings
        ansible.builtin.command: gsettings set org.gnome.desktop.interface gtk-theme "Dracula"
        become: false

    -   name: Set GTK icon theme via gsettings
        ansible.builtin.command: gsettings set org.gnome.desktop.interface icon-theme "Papirus"
        become: false

    -   name: Set color scheme to prefer dark
        ansible.builtin.command: gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
        become: false

# Next fresh installation check how to enable this without gnome, also now manual enable is needed for qt applications via qt5ct
