- hosts: localhost
  become: true
  tasks:


  - name: Set mirrors using reflector
    command: sudo reflector --country "{{ countries }}" --fastest 10 --threads `nproc` --save /etc/pacman.d/mirrorlist
