- hosts: localhost
  become: yes
  tasks:


  - name: Install power management packages
    pacman:
      name:
      - tlp
      - tlp-rdw
      - acpi
      - acpi_call
      state: present


  - name: Enable TLP service
    systemd:
      name: tlp
      enabled: true
      state: started


  - name: Mask systemd-rfkill.service
    systemd:
      name: systemd-rfkill.service
      masked: true


  - name: Mask systemd-rfkill.socket
    systemd:
      name: systemd-rfkill.socket
      masked: true
