  - name: Setup Tmux Plugin Manager
    hosts: localhost
    tasks:

      - name: Clone TPM repository
        become: false
        ansible.builtin.command: git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
