---
- name: Configure DNS over TLS with systemd-resolved
  hosts: localhost
  become: true 
  tasks:

    - name: Remove conflicting DNS services
      pacman:
        name:
          - dnsmasq
          - unbound
        state: absent

    - name: Install systemd-resolvconf (for resolvctl)
      pacman:
        name: systemd-resolvconf
        state: present

    - name: Enable and start systemd-resolved service
      systemd:
        name: systemd-resolved
        enabled: true 
        state: started

    - name: Configure DNS servers with DNS over TLS in resolved.conf
      lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: '^DNS='
        line: 'DNS=1.1.1.1#cloudflare-dns.com 8.8.8.8#dns.google 9.9.9.9#dns.quad9.net'
      notify: Restart systemd-resolved

    - name: Enable DNSOverTLS in resolved.conf
      lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: '^DNSOverTLS='
        line: 'DNSOverTLS=yes'
      notify: Restart systemd-resolved

    - name: Ensure Domains setting is correct in resolved.conf
      lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: '^Domains='
        line: 'Domains=~.'
      notify: Restart systemd-resolved

    - name: Ensure /etc/resolv.conf points to systemd-resolved stub resolver
      file:
        src: /run/systemd/resolve/stub-resolv.conf
        dest: /etc/resolv.conf
        state: link
        force: true 

  handlers:
    - name: Restart systemd-resolved
      systemd:
        name: systemd-resolved
        state: restarted

